import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  moveCard: {
    backgroundColor: '#fff',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#eee',
    marginBottom: 10,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOpacity: 0.06,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 2,
  },
  moveHeader: {
    borderBottomWidth: 2,
    borderBottomColor: '#e63946',
    padding: 12,
    backgroundColor: '#e63946',
  },
  moveHeaderText: {
    fontWeight: 'bold',
    fontSize: 16,
    color: '#fff',
    letterSpacing: 0.5,
  },
  moveRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f1f1',
  },
  moveLabel: {
    color: '#22223b',
    fontWeight: '600',
    fontSize: 13,
    flex: 1.2,
  },
  moveValue: {
    color: '#22223b',
    fontSize: 13,
    flex: 1.5,
    textAlign: 'right',
  },
  container: { 
    flex: 1, 
    backgroundColor: "#f8f9fa" 
  },
  scroll: { 
    flexGrow: 1, 
    justifyContent: "center", 
    alignItems: "center", 
    padding: 20, 
    paddingTop: 60 
  },
  logoContainer: { 
    alignItems: "center", 
    marginBottom: 40, 
    marginTop: 40 
  },
  companyLogo: { 
    width: 280, 
    height: 100, 
    marginBottom: 10 
  },
  appLogo: { 
    width: 140, 
    height: 60 
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
    elevation: 4,
  },
  cardHeader: { 
    flexDirection: "row", 
    justifyContent: "space-between", 
    alignItems: "center" 
  },
  cardTitle: { 
    fontSize: 18, 
    fontWeight: "600", 
    color: "#1d3557" 
  },
  cardContent: { 
    marginTop: 10 
  },
  button: { 
    backgroundColor: "#e63946", 
    paddingVertical: 14, 
    borderRadius: 8, 
    marginTop: 10, 
    alignItems: "center" 
  },
  buttonText: { 
    color: "#fff", 
    fontWeight: "600", 
    fontSize: 16 
  },
  message: { 
    marginTop: 10, 
    fontSize: 14, 
    color: "red", 
    textAlign: "center" 
  },
  moveHeaderSubtext: {
    fontSize: 12,
    color: '#fff',
    opacity: 0.9,
    marginTop: 2,
  },
  statusBadge: {
    backgroundColor: 'rgba(255,255,255,0.25)',
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  statusBadgeText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 12,
  },
  cardPreview: {
    backgroundColor: '#f8f9fa',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
  },
  cardPreviewText: {
    fontSize: 13,
    color: '#666',
  },
  sectionHeader: {
    backgroundColor: '#f8f9fa',
    borderBottomWidth: 2,
    borderBottomColor: '#e63946',
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginTop: 18,
  },
  sectionHeaderText: {
    fontWeight: 'bold',
    fontSize: 15,
    color: '#22223b',
    letterSpacing: 0.5,
  },
  paymentsCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#eee',
    marginTop: 8,
    marginBottom: 8,
    padding: 8,
  },
  paymentHistoryTitle: {
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 8,
    color: '#22223b',
  },
  paymentTableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f8f9fa',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingVertical: 6,
  },
  paymentTableCellHeader: {
    flex: 1,
    fontWeight: 'bold',
    color: '#22223b',
    fontSize: 13,
    textAlign: 'center',
  },
  paymentTableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f1f1',
    paddingVertical: 6,
    backgroundColor: '#fff',
  },
  paymentTableCell: {
    flex: 1,
    fontSize: 13,
    color: '#22223b',
    textAlign: 'center',
  },
  paymentDetailsRow: {
    backgroundColor: '#f8f9fa',
    padding: 8,
    borderRadius: 6,
    marginVertical: 4,
  },
  paymentDetailsLabel: {
    fontWeight: 'bold',
    color: '#22223b',
    fontSize: 13,
    marginTop: 4,
  },
  paymentDetailsValue: {
    color: '#22223b',
    fontSize: 13,
    marginBottom: 4,
  },
  addPaymentButton: {
    borderWidth: 2,
    borderColor: '#e63946',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 12,
  },
  addPaymentButtonText: {
    color: '#e63946',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 1,
  },
  invoiceCard: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#eee',
    marginTop: 8,
    marginBottom: 8,
    padding: 8,
  },
  loginInput: {
    backgroundColor: "#f1f1f1",
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
    minWidth: 280,
  },
  resetButton: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ccc",
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    marginTop: 10,
    alignItems: "center",
    alignSelf: "center",
  },
  resetButtonText: {
    color: "#888",
    fontWeight: "400",
    fontSize: 13,
  },
  companyLogoBottom: {
    alignItems: "center",
    marginTop: 40,
  },
  settingsContainer: {
    flex: 1,
  },
  settingsTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#22223b',
    marginBottom: 24,
    textAlign: 'center',
  },
  logoutButton: {
    flexDirection: 'row',
    backgroundColor: '#e63946',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  logoutButtonText: {
    color: '#fff',
    fontWeight: 'bold',
    fontSize: 18,
    marginLeft: 12,
  },
  viewDataButton: {
    flexDirection: 'row',
    backgroundColor: '#fff',
    borderWidth: 2,
    borderColor: '#e63946',
    paddingVertical: 16,
    paddingHorizontal: 24,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 16,
  },
  viewDataButtonText: {
    color: '#e63946',
    fontWeight: 'bold',
    fontSize: 18,
    marginLeft: 12,
  },
  localDataContainer: {
    backgroundColor: '#fff',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#eee',
    marginTop: 16,
    padding: 16,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
    elevation: 3,
  },
  localDataHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: '#e63946',
  },
  localDataTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#22223b',
  },
  localDataScroll: {
    maxHeight: 400,
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 12,
  },
  localDataText: {
    fontSize: 12,
    fontFamily: 'monospace',
    color: '#22223b',
  },
  calendarTaskItem: {
    backgroundColor: '#fff',
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#eee',
    padding: 12,
    marginBottom: 12,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowOffset: { width: 0, height: 1 },
    shadowRadius: 3,
    elevation: 2,
  },
  calendarTaskHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f1f1f1',
  },
  calendarTaskId: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#22223b',
  },
  calendarTaskStatus: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
  },
  calendarTaskStatusText: {
    fontSize: 11,
    fontWeight: 'bold',
    color: '#fff',
  },
  calendarTaskDetail: {
    fontSize: 14,
    color: '#22223b',
    marginBottom: 4,
  },
  calendarTaskLabel: {
    fontWeight: '600',
    color: '#666',
  },
  invoiceTableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f8f9fa',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    paddingVertical: 6,
  },
  invoiceTableCellHeader: {
    flex: 1,
    fontWeight: 'bold',
    color: '#22223b',
    fontSize: 13,
    textAlign: 'center',
  },
  invoiceTableRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f1f1',
    paddingVertical: 6,
    backgroundColor: '#fff',
  },
  invoiceTableCell: {
    flex: 1,
    fontSize: 13,
    color: '#22223b',
    textAlign: 'center',
  },
  invoiceSummaryContainer: {
    backgroundColor: '#f8f9fa',
    borderRadius: 8,
    padding: 12,
    marginTop: 16,
  },
  invoiceSummaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 4,
  },
  invoiceSummaryLabel: {
    fontSize: 14,
    color: '#22223b',
  },
  invoiceSummaryValue: {
    fontSize: 14,
    color: '#22223b',
    fontWeight: '600',
  },
  editInvoiceButton: {
    borderWidth: 2,
    borderColor: '#e63946',
    borderRadius: 8,
    paddingVertical: 12,
    alignItems: 'center',
    marginTop: 16,
  },
  editInvoiceButtonText: {
    color: '#e63946',
    fontWeight: 'bold',
    fontSize: 16,
    letterSpacing: 1,
  },
});
